---
- name: Using loop to provision many items
  hosts: all
  become: yes

  vars_files:
    - ./vault_hosts.yml       # moved here instead of inventory.yml

  tasks:
    - name: Install multiple packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - curl
        - git

