---
- name: Deploy Nginx on web servers
  hosts: webservers
  become: yes

  vars_files:
    - ./vault_hosts.yml


  #vars:
  #  nginx_conf_src: templates/nginx.conf.j2
  #  nginx_conf_dest: /etc/nginx/nginx.conf

  tasks:
    - name: Ensure apt cache is updated (Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure yum cache is updated (RedHat)
      ansible.builtin.yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Install Nginx on Ubuntu
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Nginx on RedHat
      ansible.builtin.yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Deploy custom Nginx configuration
      ansible.builtin.template:
        src: "{{ nginx_conf_src }}"
        dest: "{{ nginx_conf_dest }}"
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart Nginx

    - name: Ensure Nginx service is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

